sp23Team33FinalProject/Models/ViewModels/RecruiterSearchViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace sp23Team33FinalProject.Models
{
    public class RecruiterSearchViewModel
    {
        [Display(Name = "Search by Student Name:")]
        public String RecruiterName { get; set; }

        [Display(Name = "Search by Companies:")]
        public List<Int32> CompanyIDs { get; set; }
    }
}

sp23Team33FinalProject/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sp23Team33FinalProject.DAL;
using sp23Team33FinalProject.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace sp23Team33FinalProject.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private readonly AppDbContext _context;

        public CompaniesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            var query = from c in _context.Companies select c;
            ViewBag.AllCompanies = query.Count();
            // TODO restrict recuiters from changing other company details
            if (User.IsInRole("Recruiter") == true)
            {
                AppUser recruiter = await _context.Users.Include(u => u.Company)
                                                            .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

                query = query.Where(p => p.Recruiters.Contains(recruiter));
            }

            List<Company> SelectedCompanies = query.Include(c => c.Positions).ToList();

            ViewBag.SelectedCompanies = SelectedCompanies.Count();

            return View(SelectedCompanies.OrderBy(c => c.CompanyName));
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var query = from a in _context.Companies select a;
            if (id == null || _context.Companies == null)
            {
                return View("Error", new String[] { "Please specify a company to view details!" });
            }

            var company = await _context.Companies.Include(c => c.Positions)
                .FirstOrDefaultAsync(m => m.CompanyID == id);

            if (company == null)
            {
                return View("Error", new String[] { "This company does not exist in the database!" });
            }

            

                return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Create()
        {
            if(User.IsInRole("Recruiter"))
            {
                AppUser recruiter = await _context.Users.Include(u => u.Company).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                if(recruiter.Company != null)
                {
                    return View("Error", new String[] { "You are NOT authorized to create companies!" });
                }
            }
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Create([Bind("CompanyID,CompanyName,CompanyDesc,CompanyEmail,Industry1,Industry2,Industry3")] Company company)
        {
            if (User.IsInRole("Recruiter"))
            {
                AppUser recruiter = await _context.Users.Include(u => u.Company).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                if (recruiter.Company != null)
                {
                    return View("Error", new String[] { "You are NOT authorized to create companies!" });
                }
                if (ModelState.IsValid)
                {
                    _context.Add(company);
                    recruiter.Company = company;
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        [Authorize(Roles = "Recruiter, CSO")]
        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Companies == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Edit(int id, [Bind("CompanyID,CompanyName,CompanyDesc,CompanyEmail,Industry1,Industry2,Industry3")] Company company)
        {
            if (id != company.CompanyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.CompanyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        private bool CompanyExists(int id)
        {
          return (_context.Companies?.Any(e => e.CompanyID == id)).GetValueOrDefault();
        }

        public IActionResult CompanySearch()
        {
            return View();
        }

        public IActionResult DisplayCompanySearchResults(CompanySearchViewModel csvm)
        {
            // LINQ query to filter books
            var query = from c in _context.Companies select c;

            if (csvm.CompanyName != "" && csvm.CompanyName != null)
            {
                query = query.Where(c => c.CompanyName.Contains(csvm.CompanyName));
            }

            if (csvm.Location != "" && csvm.Location != null)
            {
                query = query.Where(c => c.Positions.Any(p => p.Location.Contains(csvm.Location)));
            }

            if (csvm.Industry != null)
            {
                query = query.Where(c => c.Industry1 == csvm.Industry || c.Industry2 == csvm.Industry || c.Industry3 == csvm.Industry);
            }

            if (csvm.PositionType != null)
            {
                query = query.Where(c => c.Positions.Any(p => p.PositionType == csvm.PositionType));
            }

            // select all books in query and return view with books.
            List<Company> SelectedCompanies = query.Include(c => c.Positions).ToList();

            return View("Index", SelectedCompanies.OrderBy(c => c.CompanyName));
        }
    }
}

sp23Team33FinalProject/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Runtime.Intrinsics.Arm;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sp23Team33FinalProject.DAL;
using sp23Team33FinalProject.Models;
using sp23Team33FinalProject.Utilities;

namespace sp23Team33FinalProject.Controllers
{
    [Authorize]
    public class PositionsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;


        public PositionsController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Positions
        public async Task<IActionResult> Index()
        {
            var query = from p in _context.Positions select p;
            ViewBag.AllPositions = _context.Positions.Count();

            if (User.IsInRole("Student") == true)
            {
                ISession session = HttpContext.Session;
                string dateString = session.GetString("AppDate");
                DateTime AppDate = DateTime.Parse(dateString);

                query = query.Where(p => p.Deadline >= AppDate);
                ViewBag.AllPositions = query.Count();
            }

            // TODO restrict recuiters from changing other company details
            if (User.IsInRole("Recruiter") == true)
            {
                AppUser recruiter = await _context.Users.Include(u => u.Company)
                                                            .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

                query = query.Where(p => p.Company == recruiter.Company);
                ViewBag.AllPositions = query.Count();
            }

            // selects all positions in query
            List<Position> SelectedPositions = query.Include(p => p.Company).Include(p => p.Majors).ToList();

            ViewBag.SelectedPositions = SelectedPositions.Count();

            return View(SelectedPositions.OrderBy(p => p.Deadline));
        }

        // GET: Positions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Positions == null)
            {
                return View("Error", new String[] { "Please specify a product to view!" });
            }

            Position position = await _context.Positions
            .Include(p => p.Company)
            .Include(p => p.Majors)
            .FirstOrDefaultAsync(m => m.PositionID == id);

            if (position == null)
            {
                return View("Error", new String[] { "This product was not found in the database!" });
            }

            return View(position);
        }

        // GET: Positions/Create
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Create()
        {
            ViewBag.AllCompanies = GetAllCompaniesSelectList();
            if (User.IsInRole("Recruiter"))
            {

                AppUser recruiter = await _context.Users.Include(u => u.Company).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                Company recCompany = await _context.Companies.Include(c => c.Positions).FirstOrDefaultAsync(c => c.Recruiters.Contains(recruiter));

                List<Company> companyList = new List<Company>();

                companyList.Add(recCompany);

                SelectList companySelectList = new SelectList(companyList.OrderBy(c => c.CompanyID), "CompanyID", "CompanyName");

                ViewBag.AllCompanies = companySelectList;

            }
            ViewBag.AllMajors = GetAllMajorsMultiSelectList();
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Recruiter, CSO")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PositionID,PositionTitle,PositionDescription,PositionType,Location,Deadline")] Position position, int SelectedCompany, int[] SelectedMajors)
        {
            if (ModelState.IsValid == false)
            {
                ViewBag.AllCompanies = GetAllCompaniesSelectList();
                ViewBag.AllMajors = GetAllMajorsMultiSelectList();
                return View(position);
            }

            position.Company = _context.Companies.Find(SelectedCompany);
            //Add product to database
            _context.Add(position);
            await _context.SaveChangesAsync();

            //add suppliers
            foreach (int majorID in SelectedMajors)
            {
                Major dbMajor = _context.Majors.Find(majorID);
                position.Majors.Add(dbMajor);
                await _context.SaveChangesAsync();
            }

            //go back to Index page
            return RedirectToAction(nameof(Index));
        }

        // GET: Positions/Edit/5
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("Error", new String[] { "Please specify a position to edit!" });
            }

            Position position = await _context.Positions.Include(p => p.Company).Include(p => p.Majors)
                                                     .FirstOrDefaultAsync(p => p.PositionID == id);


            if (position == null)
            {
                return View("Error", new String[] { "This position does not exist in the database!" });
            }

            if (User.IsInRole("Recruiter"))
            {
                AppUser recruiter = await _context.Users.Include(u => u.Company).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                Company recCompany = await _context.Companies.Include(c => c.Positions).FirstOrDefaultAsync(c => c.Recruiters.Contains(recruiter));
                if (position.Company != recCompany)
                {
                    return View("Error", new String[] { "You are not authorized to edit this position!" });
                }
                ISession session = HttpContext.Session;
                string dateString = session.GetString("AppDate");
                DateTime AppDate = DateTime.Parse(dateString);
                if (position.Deadline > AppDate)
                {
                    return View("Error", new String[] { "You are not authorized to edit positions after deadline!" });
                }
            }

            ViewBag.AllCompanies = GetAllCompaniesSelectList(position);
            ViewBag.AllMajors = GetAllMajorsMultiSelectList(position);
            return View(position);
        }


        // POST: Positions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Edit(int id, Position position, int SelectedCompany, int[] SelectedMajors)
        {
            if (id != position.PositionID)
            {
                return View("Error", new String[] { "There was an error.  Please try again." });
            }

            Position dbPosition = _context.Positions.Include(p => p.Company)
                                                    .Include(p => p.Majors)
                                                    .FirstOrDefault(p => p.PositionID == position.PositionID);

            if (dbPosition == null)
            {
                return View("Error", new String[] { "This position was not found! " });
            }

            if (ModelState.IsValid == false)
            {
                //re-populate the view bag
                ViewBag.AllCompany = GetAllCompaniesSelectList(dbPosition);
                ViewBag.AllMajors = GetAllMajorsMultiSelectList(dbPosition);


                //go back to the view
                return View(position);
            }

            try
            {
                //create the list of products to delete
                List<Major> MajorsToRemove = new List<Major>();

                //find the ones that aren't on the new list
                foreach (Major major in dbPosition.Majors)
                {
                    if (SelectedMajors.Contains(major.MajorId) == false) //existing major is not in new list
                    {
                        MajorsToRemove.Add(major);
                    }
                }

                //remove the items in the list
                foreach (Major major in MajorsToRemove)
                {
                    dbPosition.Majors.Remove(major);
                    await _context.SaveChangesAsync();
                }

                //now add all the new suppliers
                foreach (int majorID in SelectedMajors)
                {
                    if (dbPosition.Majors.Any(m => m.MajorId == majorID) == false)
                    {
                        //find the supplier in the database
                        Major dbMajor = _context.Majors.Find(majorID);

                        //add to list
                        dbPosition.Majors.Add(dbMajor);

                        //save changes
                        await _context.SaveChangesAsync();
                    }
                }

                //change remaining properties
                Company dbCompany = await _context.Companies
                    .Include(c => c.Positions)

sp23Team33FinalProject/Views/Home/CSOIndex.cshtml
@model IEnumerable<sp23Team33FinalProject.Models.AppUser>

@{
    ViewData["Title"] = "CSO Index";
}

<h1>Index</h1>

<form asp-action="Index" asp-controller="Home" method="get">
</form>

<!--TODO: add an view profile button-->

@if (User.Identity.IsAuthenticated && User.IsInRole("CSO"))
{
    <p>
        <a asp-action="RegisterCSO" asp-controller="Account">Create New</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("CSO"))
                    {
                        <a asp-action="EditCSOProfile" asp-controller="Account" asp-route-csoID="@item.Id">Edit</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

sp23Team33FinalProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<h1>Welcome to Our Recruitment Site!</h1>

@if (User.Identity.IsAuthenticated)
{
    <a asp-action="Index" asp-controller="Positions" class="btn btn-info">View Positions</a>
    <a asp-action="Index" asp-controller="Companies" class="btn btn-info">View Companies</a>
    <a asp-action="Index" asp-controller="Applications" class="btn btn-info">View Applications</a>

    if (User.IsInRole("CSO"))
    {
        <a asp-action="StudentsIndex" asp-controller="Home" class="btn btn-info">View Student Profiles</a>
        <a asp-action="RecruitersIndex" asp-controller="Home" class="btn btn-info">View recruiter profiles</a>
        <a asp-action="CSOIndex" asp-controller="Home" class="btn btn-info">View CSO Profiles</a>
        <a asp-action="Index" asp-controller="Interviews" class="btn btn-info">View Interview Schedule</a>
        <a asp-action="ReserveRoom" asp-controller="Interviews" class="btn btn-info">Reserve Room</a>
        <a asp-action="RoomVisual" asp-controller="Interviews" class="btn btn-info">Room Booking Chart</a>
    }

    if (User.IsInRole("Student"))
    {
        <a asp-action="Index" asp-controller="Interviews" class="btn btn-info">View my Interviews</a>
    }

    if (User.IsInRole("Recruiter"))
    {
        <a asp-action="StudentsIndex" asp-controller="Home" class="btn btn-info">View Student Profiles</a>
        <a asp-action="Index" asp-controller="Interviews" class="btn btn-info">View Interviews</a>
        <a asp-action="RoomVisual" asp-controller="Interviews" class="btn btn-info">Room Booking Chart</a>
    }

}

sp23Team33FinalProject/Views/Home/RecruiterSearch.cshtml
@model sp23Team33FinalProject.Models.RecruiterSearchViewModel

@{
    ViewData["Title"] = "RecruiterSearch";
}

<h1>Position Search</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DisplayRecruiterSearchResults" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecruiterName" class="control-label"></label>
                <input asp-for="RecruiterName" class="form-control" />
                <span asp-validation-for="RecruiterName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="CompanyIDs" class="control-label"></label>
                @Html.ListBoxFor(model => model.CompanyIDs, (MultiSelectList)ViewBag.AllCompanies, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="RecruitersIndex">Back to List</a>
</div>

sp23Team33FinalProject/Views/Home/RecruitersIndex.cshtml
@model IEnumerable<sp23Team33FinalProject.Models.AppUser>

@{
    ViewData["Title"] = "Recruiter Index";
}

<h1>Index</h1>

<form asp-action="Index" asp-controller="Home" method="get">
    <p class="form-group">
        <a asp-action="RecruiterSearch" class="btn btn-success">Advanced Search</a>
        <a asp-action="RecruitersIndex" class="btn btn-danger">Show All</a>
    </p>
</form>

@if (User.Identity.IsAuthenticated && User.IsInRole("CSO"))
{
    <p>
        <a asp-action="RegisterRecruiter" asp-controller="Account" >Create New</a>
    </p>
}

<n>Displaying @ViewBag.SelectedRecruiters of @ViewBag.AllRecruiters Recruiters</n>

<!--TODO: add an view profile button-->
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company.CompanyName)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company.CompanyName)
                </td>
                <td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("CSO"))
                    {
                        <a asp-action="EditRecruiterProfile" asp-controller="Account" asp-route-recruiterID="@item.Id">Edit</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

sp23Team33FinalProject/Views/Home/SetDate.cshtml
@model sp23Team33FinalProject.Models.SetDateViewModel

@{
    ViewData["Title"] = "Set App Date";
}

<h1>Set App Date</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SetDate" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SetDate" class="control-label"></label>
                <input asp-for="SetDate" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="RecruitersIndex">Back to List</a>
</div>

sp23Team33FinalProject/Views/Home/StudentSearch.cshtml
@model sp23Team33FinalProject.Models.StudentSearchViewModel

@{
    ViewData["Title"] = "StudentSearch";
}

<h1>Position Search</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DisplayStudentSearchResults" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <br/>
            <div>
                <div class="form-group">
                    <label asp-for="GradYear" class="control-label"></label>
                    <select asp-for="GradYear" asp-items="Html.GetEnumSelectList<GraduationYearEnum>()" class="form-control">
                        <option selected="selected" value="">All Grad Years</option>
                    </select>
                    <span asp-validation-for="GradYear" class="text-danger"></span>
                </div>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="MajorIDs" class="control-label"></label>
                @Html.ListBoxFor(model => model.MajorIDs, (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label asp-for="GPA" class="control-label"></label>
                <input asp-for="GPA" type="number" step="0.1" class="form-control" />
                <span asp-validation-for="GPA" class="text-danger"></span>
            </div>
            <!--Default to "less than" for GPA search type-->
            <div class="form-group">
                <label asp-for="GPASearchType" class="control-label"></label>
                <input type="radio" class="radio" checked="checked" asp-for="GPASearchType" value="@GPASearchType.LessThan" /> Less Than
                <input type="radio" class="radio" asp-for="GPASearchType" value="@GPASearchType.GreaterThan" /> Greater Than
                <span asp-validation-for="GPASearchType" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="PositionType" class="control-label"></label>
                <select asp-for="PositionType" asp-items="Html.GetEnumSelectList<PositionType>()" class="form-control">
                    <option selected="selected" value="">All Position Types</option>
                </select>
                <span asp-validation-for="PositionType" class="text-danger"></span>
            </div>       

            <br />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="StudentsIndex">Back to List</a>
</div>

sp23Team33FinalProject/Views/Home/StudentsIndex.cshtml
@model IEnumerable<sp23Team33FinalProject.Models.AppUser>

@{
    ViewData["Title"] = "Student Index";

}



<h1>List of Students</h1>

<form asp-action="Index" asp-controller="Home" method="get">
    <p class="form-group">
        <a asp-action="StudentSearch" class="btn btn-success">Advanced Search</a>
        <a asp-action="StudentsIndex" class="btn btn-danger">Show All</a>
    </p>
</form>

@if (User.Identity.IsAuthenticated && User.IsInRole("CSO"))
{
    <p>
        <a asp-action="Register" asp-controller="Account">Create New</a>
    </p>
}

<n>Displaying @ViewBag.SelectedStudents of @ViewBag.AllStudents Students</n>

<!--TODO: add an view profile button-->
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GraduationYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Major.MajorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GPA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PositionType)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GraduationYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Major.MajorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GPA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PositionType)
                </td>
                <td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("CSO"))
                    {
                        <a asp-action="EditProfile" asp-controller="Account" asp-route-studentID="@item.Id">Edit</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>