sp23Team33FinalProject/Models/Position.cs
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using System.ComponentModel.DataAnnotations;

namespace sp23Team33FinalProject.Models
{

    public class Position
    {
        public Int32 PositionID { get; set; }

        [Display(Name = "Position Title:")]
        [Required(ErrorMessage = "Position title is required.")]
        public String PositionTitle { get; set; }

        [Display(Name = "Position Description:")]
        public String? PositionDescription { get; set; }

        [Display(Name = "Position Type:")]
        [Required(ErrorMessage = "Position type is required.")]
        public PositionType PositionType { get; set; }

        [Display(Name = "Location:")]
        [Required(ErrorMessage = "Location is required.")]
        public String Location { get; set; }

        [Display(Name = "Deadline:")]
        [Required(ErrorMessage = "Deadline is required.")]
        public DateTime Deadline { get; set; }
        public Position()
        {
            Majors ??= new List<Major>();
            Applications ??= new List<Application>();
        }

        // navigational properties
        public Company Company { get; set; }
        public List<Application> Applications { get; set; }
        public List<Major> Majors { get; set; }
    }
}

sp23Team33FinalProject/Models/ViewModels/PositionSearchViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace sp23Team33FinalProject.Models
{ 
    public class PositionSearchViewModel
    {
        [Display(Name = "Search by Company:")]
        public List<Int32> CompanyIDs { get; set; }

        [Display(Name = "Search by Position Title:")]
        public String PositionTitle { get; set; }

        // BONUS: search by multiple industries??
        [Display(Name = "Search by Industry(s):")]
        public Industry? Industry { get; set; }

        [Display(Name = "Search by Position Type:")]
        public PositionType? PositionType { get; set; }

        [Display(Name = "Search by Major:")]
        public List<Int32> MajorIDs { get; set; }

        [Display(Name = "Search by Location:")]
        public String Location { get; set; }

    }
}

sp23Team33FinalProject/Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sp23Team33FinalProject.DAL;
using sp23Team33FinalProject.Models;

namespace sp23Team33FinalProject.Controllers
{
    [Authorize]
    public class InterviewsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public InterviewsController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Interviews
        public async Task<IActionResult> Index()
        {
            var query = from i in _context.Interviews select i;
            if (User.IsInRole("Student") == true)
            {
                query = query.Where(i => i.Student.UserName == User.Identity.Name);
            }

            if (User.IsInRole("Recruiter") == true)
            {
                // find recruiter
                AppUser recruiter = await _context.Users.Include(u => u.Company)
                    .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                // restrict query to only application for positions in rec's company
                query = query.Where(i => i.Position.Company == recruiter.Company);

            }

            List<Interview> SelectedIntervierws = await query.Include(i => i.Host)
                                                                .Include(a => a.Position)
                                                                .ThenInclude(p => p.Company)
                                                                .Include(a => a.Application)
                                                                .Include(i => i.Student)
                                                                .ToListAsync();

            return View(SelectedIntervierws.OrderBy(a => a.InterviewDateTime));
        }

        // GET: Interviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Interviews == null)
            {
                return NotFound();
            }

            var interview = await _context.Interviews
                .Include(i => i.Student)
                .Include(i => i.Application)
                .ThenInclude(i => i.Position).ThenInclude(p => p.Company)
                .Include(i => i.Host)
                .FirstOrDefaultAsync(m => m.InterviewID == id);

            if (interview == null)
            {
                return NotFound();
            }

            return View(interview);
        }

        // GET: Interviews/Create
        public IActionResult Create()
        {
            ViewData["AppForeignKey"] = new SelectList(_context.Applications, "ApplicationID", "ApplicationID");
            return View();
        }

        // POST: Interviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InterviewID,InterviewDateTime,Room,AppForeignKey")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                _context.Add(interview);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppForeignKey"] = new SelectList(_context.Applications, "ApplicationID", "ApplicationID", interview.AppForeignKey);
            return View(interview);
        }

        // edit interview host as  drop down list to be anyone from the company

        // GET: Interviews/Edit/5
        [Authorize(Roles ="Recruiter, CSO")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Interviews == null)
            {
                return NotFound();
            }

            var interview = await _context.Interviews.Include(i => i.Host).FirstOrDefaultAsync(i => i.InterviewID == id);

            if (interview == null)
            {
                return NotFound();
            }
            ViewBag.AllHosts = await GetAllHostsAsync(interview.Host.Id);
            //ViewData["AppForeignKey"] = new SelectList(_context.Applications, "ApplicationID", "ApplicationID", interview.AppForeignKey);
            return View(interview);
        }

        // POST: Interviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> Edit(int id, Interview interview)
        {
            if (id != interview.InterviewID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InterviewExists(interview.InterviewID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AppForeignKey"] = new SelectList(_context.Applications, "ApplicationID", "ApplicationID", interview.AppForeignKey);
            ViewBag.AllHosts = await GetAllHostsAsync(interview.Host.Id);
            return View(interview);
        }

        // GET: Interviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Interviews == null)
            {
                return NotFound();
            }

            var interview = await _context.Interviews
                .Include(i => i.Application)
                .ThenInclude(i => i.Position)
                .Include(i => i.Host)
                .Include(i => i.Student)


                .FirstOrDefaultAsync(m => m.InterviewID == id);
            if (interview == null)
            {
                return NotFound();
            }

            ISession session = HttpContext.Session;
            string dateString = session.GetString("AppDate");
            DateTime AppDate = DateTime.Parse(dateString);

            if (AppDate.AddHours(24) >= interview.InterviewDateTime)
            {
                return View("Error", new String[] { "Cannot cancel interview within 24 hours of start time!" });
            }


            return View(interview);
        }

        // POST: Interviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Interviews == null)
            {
                return Problem("Entity set 'AppDbContext.Interviews'  is null.");
            }

            var interview = await _context.Interviews.Include(i => i.Student).Include(i => i.Application).FirstOrDefaultAsync(i => i.InterviewID == id);

            if(interview.Student != null)
            {
                AppUser student = await _context.Users.Include(s => s.StudentInterviews).FirstOrDefaultAsync(u => u.UserName == interview.Student.UserName);
                if (student != null)
                {
                    student.StudentInterviews.Remove(interview);
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
            }
            
            if(interview.Application != null)
            {
                Application application = await _context.Applications.Include(a => a.Interview).FirstOrDefaultAsync(a => a.ApplicationID == interview.Application.ApplicationID);
                if (application != null)
                {
                    application.Interview = null;
                    _context.Update(application);
                    await _context.SaveChangesAsync();
                }
            }

            interview.Student = null;
            interview.Application = null;

            _context.Update(interview);
            await _context.SaveChangesAsync();
            
            if(User.IsInRole("Recruiter") || User.IsInRole("CSO"))
            {
                if (interview != null)
                {
                    _context.Interviews.Remove(interview);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Recruiter, CSO")]
        public async Task<IActionResult> StudentScheduler()
        {
            List<Interview> SelectedInterviews;

            if (User.IsInRole("Admin"))
            {
                SelectedInterviews = await _context.Interviews
                                 .Include(o => o.Application)
                                 .ThenInclude(o => o.Position)
                                 .Include(o => o.Host)
                                 .ToListAsync();
            }
            if (User.IsInRole("Student")) //user is a customer
            {
                AppUser appUser = await _userManager.FindByNameAsync(User.Identity.Name);
                SelectedInterviews = await _context.Interviews

sp23Team33FinalProject/Views/Positions/Create.cshtml
@model sp23Team33FinalProject.Models.Position

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PositionTitle" class="control-label"></label>
                <input asp-for="PositionTitle" class="form-control" />
                <span asp-validation-for="PositionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionDescription" class="control-label"></label>
                <input asp-for="PositionDescription" class="form-control" />
                <span asp-validation-for="PositionDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PositionType" class="control-label"></label>
                <select asp-for="PositionType" asp-items="Html.GetEnumSelectList<PositionType>()" class="form-control">
                </select>
                <span asp-validation-for="PositionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Company:</label>
                @Html.DropDownList("SelectedCompany", (SelectList)ViewBag.AllCompanies, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Accepted Majors:</label>
                @Html.ListBox("SelectedMajors", (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

sp23Team33FinalProject/Views/Positions/Delete.cshtml
@model sp23Team33FinalProject.Models.Position

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Position</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PositionTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PositionTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PositionDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PositionDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PositionType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PositionType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PositionID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

sp23Team33FinalProject/Views/Positions/Details.cshtml
@model sp23Team33FinalProject.Models.Position

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Position</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PositionTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PositionTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PositionDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PositionDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PositionType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PositionType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.Industry1)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.Industry1)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.Industry2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.Industry2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.Industry3)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.Industry3)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
</div>

<h5>Accepted Majors</h5>
<table class="table table-bordered">
    <tr>
        <th>Majors:</th>
    </tr>
    @foreach (Major major in Model.Majors)
    {
        <tr>
            <td>@major.MajorName</td>
        </tr>
    }
</table>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PositionID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

sp23Team33FinalProject/Views/Positions/Edit.cshtml
@model sp23Team33FinalProject.Models.Position

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit"> @*method="post"> @*check if "post"" helps*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PositionID" />
            <div class="form-group">
                <label asp-for="PositionTitle" class="control-label"></label>
                <input asp-for="PositionTitle" class="form-control" />
                <span asp-validation-for="PositionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionDescription" class="control-label"></label>
                <input asp-for="PositionDescription" class="form-control" />
                <span asp-validation-for="PositionDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PositionType" class="control-label"></label>
                <select asp-for="PositionType" asp-items="Html.GetEnumSelectList<PositionType>()" class="form-control">
                </select>
                <span asp-validation-for="PositionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Company:</label>
                @Html.DropDownList("SelectedCompany", (SelectList)ViewBag.AllCompanies, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Accepted Majors:</label>
                @Html.ListBox("SelectedMajors", (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

sp23Team33FinalProject/Views/Positions/Index.cshtml
@model IEnumerable<sp23Team33FinalProject.Models.Position>

@{
    ViewData["Title"] = "Index";
}

<h1>List of Positions</h1>

<form asp-action="Index" asp-controller="Home" method="get">
    <p class="form-group">
        <a asp-action="PositionSearch" class="btn btn-success">Advanced Search</a>
        <a asp-action="Index" class="btn btn-danger">Show All</a>
    </p>
</form>

<n>Displaying @ViewBag.SelectedPositions of @ViewBag.AllPositions Positions</n>

@if (User.Identity.IsAuthenticated && (User.IsInRole("Recruiter") || User.IsInRole("CSO")))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
    
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PositionTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PositionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PositionTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PositionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Deadline)
                </td>
                <td>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a asp-action="Details" asp-route-id="@item.PositionID">Details</a> 
                        <span>|</span>

                        if (User.IsInRole("Recruiter") || User.IsInRole("CSO"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.PositionID">Edit</a>
                            <span>|</span>
                            <a asp-action="Delete" asp-route-id="@item.PositionID">Delete</a>
                            <span>|</span>
                            <a asp-action="Invite" asp-controller="Interviews" asp-route-positionID="@item.PositionID">Invite Students</a>
                            <span>|</span>
                            if(User.IsInRole("Recruiter"))
                            {
                                <a asp-action="ReserveRoom" asp-controller="Interviews" asp-route-positionID="@item.PositionID">Reserve Rooms</a>
                            }
                        }

                        if (User.IsInRole("Student"))
                        {
                            <a asp-action="ApplyPosition" asp-controller="Account" asp-route-positionID="@item.PositionID">Apply</a>
                        }
                        
                    }
                    
                </td>
         
            </tr>
         }

    </tbody>
</table>

sp23Team33FinalProject/Views/Positions/Invite.cshtml
@model sp23Team33FinalProject.Models.Position

@{
    ViewData["Title"] = "Invite";
}

<h1>Invite Students to Interview</h1>
<br />
<p>Send interviews invitations to students that applied</p>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Invite">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="PositionID" />*@

            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

sp23Team33FinalProject/Views/Positions/PositionSearch.cshtml
@model sp23Team33FinalProject.Models.PositionSearchViewModel

@{
    ViewData["Title"] = "PositionSearch";
}

<h1>Position Search</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DisplaySearchResults" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompanyIDs" class="control-label"></label>
                @Html.ListBoxFor(model => model.CompanyIDs, (MultiSelectList)ViewBag.AllCompanies, new { @class = "form-control" })
            </div>
            <!--
            <div class="form-group">
                <label asp-for="CompanyID" class="control-label"></label>
                Html.DropDownListFor(model => model.CompanyID, (SelectList)ViewBag.AllCompanies, new { class = "form-control" })
            </div>
            -->
            <br />
            <div class="form-group">
                <label asp-for="PositionTitle" class="control-label"></label>
                <input asp-for="PositionTitle" class="form-control" />
                <span asp-validation-for="PositionTitle" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Industry" class="control-label"></label>
                <select asp-for="Industry" asp-items="Html.GetEnumSelectList<Industry>()" class="form-control">
                    <option selected="selected" value="">All Industries</option>
                </select>
                <span asp-validation-for="Industry" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="PositionType" class="control-label"></label>
                <select asp-for="PositionType" asp-items="Html.GetEnumSelectList<PositionType>()" class="form-control">
                    <option selected="selected" value="">All Position Types</option>
                </select>
                <span asp-validation-for="PositionType" class="text-danger"></span>
            </div>
            <br />
            <!--
            <div class="form-group">
                <label asp-for="MajorID" class="control-label"></label>
                Html.DropDownListFor(model => model.MajorID, (SelectList)ViewBag.AllMajors, new { class = "form-control" })
            </div>
            -->            
            <div class="form-group">
                <label asp-for="MajorIDs" class="control-label"></label>
                @Html.ListBoxFor(model => model.MajorIDs, (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

sp23Team33FinalProject/Views/Positions/RecruiterIndex.cshtml
@model IEnumerable<sp23Team33FinalProject.Models.Position>


@{
    ViewData["Title"] = "RecruiterIndex";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PositionTitle)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PositionTitle)
                </td>
                <td>
                    <a asp-controller="Interviews" asp-action="SchedMaker" asp-route-id="@item.PositionID">Set Interview Schedule</a>
                </td>
                <td>
                    <a asp-controller="Applications" asp-action="Invite" asp-route-id="@item.PositionID">Invite Student to Interview</a>
                </td>
                @*<td>
            @Html.ActionLink("SchedMaker", "SchedMaker", new { id = item.Application.Position.PositionID })
        </td>*@
            </tr>

        }
    </tbody>
</table>